version: '3.2'

networks:
    default:
        external:
          name: iae_network
services:
    api:
        image: iae:1.0
        ports:
            - 3001:3000
        volumes:
            - .:/app
            - node_modules:/app/node_modules
            - iae_uploads:/app/public/uploads
        environment:
            - DATABASE_USER=iae
            - DATABASE_PASSWORD=password
            - DATABASE_HOST=db
            - DATABASE_NAME=iae_development
            - RAILS_ENV=development
volumes:
    db_data:
    node_modules:
    iae_uploads:
        external: true
