version: '3.2'

networks:
    default:
        external:
          name: iae_network
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: iaeapi:tecc1.0
        ports:
            - 3001:3000
        volumes:
            - .:/app
            - iae_uploads:/app/public/uploads
        env_file: .env
        entrypoint: ./entrypoints/docker-entrypoint.sh
volumes:
    iae_uploads:
        external: true
